### ISSUE TITLE
[question] Useless 생성 규칙 제거에 대해서(2018기출문제)

### ISSUE THREAD

**Issue by Juhyeok0202** [PLASS-Lab/FLT#3]
※6-(1) 기출 문제를 푸는 과정에서 헷갈리는 부분이 있어 질문 남깁니다.

먼저, TN집합에 해당하는 심벌들을 구했습니다.
TN={S,B,C} 따라서,  NTN={A}이므로,  
LHS가 A 심벌인 경우는 해당 생성 규칙 모두를 제거하였고,
RHS가 A 심벌인 경우는 A를 가진 RHS만 제거 하였습니다.

다음과 같이 생성 규칙이 남았습니다.
S->BaS | epsilon
B->cSd | a
C->cSa | epsilon

이 다음, 접근 가능한 심벌인 AS집합에 해당하는 심벌을 구하려고 하였습니다. 
이때, NTN 심벌을 제거한 생성규칙에서는 C심벌에 접근할 수가 없습니다. 

따라서, 헷갈렸던 점은 "NTN symbols을 제거하지 않은 상태에서 AS을 구해야하는지" or "NTN symbols을 제거한 상태에서 AS을 구하여 C 심벌을 Inaccesible Symbol로 보아야하는 것인지"에 대해서 전자가 맞다고 생각 중인데, 맞는지 확인 받고 싶습니다!``

**Comment by PLASS-Lab** [comment]
불필요한 생성규칙을 제거하는 과정은 병렬적이 아니라 단계적으로 이루어져야 합니다.
1. Terminaint nonterminal 심볼을 계산하고 이에 해당하지 않는 생성규칙을 모두 제거한 후,
2. Accessible 심볼을 계산하여 해당하지 않는 규칙을 제거합니다.
